local footsteps = {}

footsteps.materialMap = {
	[Enum.Material.Fabric] = 		"Carpet",
	
	[Enum.Material.Slate] = 		"Concrete",
	[Enum.Material.Concrete] = 		"Concrete",
	[Enum.Material.Brick] = 		"Concrete",
	[Enum.Material.Cobblestone] = 	"Concrete",
	[Enum.Material.Sandstone] =		"Concrete",
	[Enum.Material.Rock] = 			"Concrete",
	[Enum.Material.Basalt] = 		"Concrete",
	[Enum.Material.CrackedLava] = 	"Concrete",
	[Enum.Material.Asphalt] = 		"Concrete",
	[Enum.Material.Limestone] = 	"Concrete",
	[Enum.Material.Pavement] = 		"Concrete",
	[Enum.Material.Pebble] = 		"Concrete",
	
	[Enum.Material.Ground] = 		"Dirt",
	[Enum.Material.Mud] = 			"Dirt",

	[Enum.Material.Grass] = 		"Grass",
	[Enum.Material.LeafyGrass] = 	"Grass",
	
	[Enum.Material.Sand] = 			"Sand",
	[Enum.Material.Salt] = 			"Sand",
	
	[Enum.Material.Snow] = 			"Snow",
	[Enum.Material.Glacier] = 		"Snow",
	
	[Enum.Material.Plastic] = 		"Tile",
	[Enum.Material.Marble] = 		"Tile",
	[Enum.Material.Granite] = 		"Tile",
	[Enum.Material.SmoothPlastic] = "Tile",

	[Enum.Material.Wood] = 			"Wood",
	[Enum.Material.WoodPlanks] = 	"WoodPlank",
	
	[Enum.Material.CorrodedMetal] = "Metal",
	[Enum.Material.DiamondPlate] = 	"Metal",
	[Enum.Material.Metal] = 		"Metal",
	[Enum.Material.Foil] = 			"Metal",

	[Enum.Material.Ice] = 			"Glass",
	[Enum.Material.Glacier] = 		"Glass",
	[Enum.Material.Glass] = 		"Glass",
	[Enum.Material.Neon] = 			"Glass",
	[Enum.Material.ForceField] = 	"Glass",
}

return footsteps
